spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nanobank_ledger
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:nanobank}
    password: ${DB_PASSWORD:nanobank123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Deshabilitar H2 en dev
  h2:
    console:
      enabled: false
